apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
spec:
  serviceName: "not-applicable"
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image:  docker.arvancloud.ir/mysql
          ports:
            - containerPort:  3306
              name:  mysql
          envFrom:
            - configMapRef:
                name: mysql-configmap
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mysql-pv
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc
