# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: eval-rest-config
data:
  MYSQL_DB: evaluation
  MYSQL_PORT: "3306"
  DEBUG : ""
  TEST_QUEUE: Test_Queue
  RABBIT_HOST: rabbitmq

